### ISSUE TITLE
Create email verification recipe

### ISSUE THREAD

**Issue by nkshah2** [supertokens/supertokens-web-js#1]
Refer to email verification in supertokens-auth-react and

- [ ] Plan out how we expect users to interact with this recipe (flows, different actions they might need to use the SDK for etc)
- [ ] Come up with a plan for functionality that this recipe will need to expose
- [ ] Configuration for the recipe and signatures/return types for functions exposed to the user

**Comment by nkshah2** [comment]
User = SuperTokens User

## User Flow

<img src="https://user-images.githubusercontent.com/18233774/149133525-2211eefb-9809-4370-8014-45ef191f8df2.png" width="600px" height="400px"/>

In general there would be 4 states that the user would require when implementing email verification

1. Sending the verification email (and handling resending). This state includes logout in the screenshot to make it consistent with the UI of auth-react
2. State where a user has clicked the verification link after already verifying once
3. When the token for verification has expired
4. When verification fails or some other error occurs

Outside of this flow, the user would also need a way to check if an email is verified at any given point

## Functions that need to be exposed by this recipe

- `sendVerificationEmail`
    - Calls the `/{apiBasePath}/user/email/verify/token POST` API (applying pre api hooks)
    - Throws `{status: "EMAIL_ALREADY_VERIFIED_ERROR"}` if the email was already verified

```ts
async function sendVerificationEmail(): Promise<{ status: "EMAIL_ALREADY_VERIFIED_ERROR" | "OK" }> {
}
```

- `isEmailVerified`
    - Calls the `/{apiBasePath}/user/email/verify GET` API

```ts
async function isEmailVerified(): Promise<boolean> {}
```

- `verifyEmail`
    - Calls the `/{apiBasePath}/user/email/verify POST` API
    - Accepts a token as a param to be used for verification. If no token is provided, it attempts to read it from the query string for the current location. If both are undefined, throws `{status: "EMAIL_VERIFICATION_INVALID_TOKEN_ERROR"}`

```ts
async function verifyEmail(
    token?: string,
): Promise<{ status: "EMAIL_VERIFICATION_INVALID_TOKEN_ERROR" | "OK" }> {}
```

## User Actions

1. Send verification email (either on page load or by clicking resend): using `sendVerificationEmail`
2. Log the user out: Using signOut from one of the parent recipes of email verification
3. Continue after verification
4. Continue after link expiry

For 3 and 4, there is no straightforward way for the SDK to provide functions and it is probably best to let the user handle this one themselves. The SDK could set a flag in localstorage for whether or not email is verified ("EMAIL_VERIFIED", "EMAIL_VERIFICATION_FAILED" etc) to allow the users easier handling but it might be best to not handle this at all.

## Hooks (Events) the user can subscribe too 
- VERIFY_EMAIL_SENT
- EMAIL_VERIFIED_SUCCESSFUL
- EMAIL_VERIFICATION_FAILED: Triggered whenever an error occurs when calling `verifyEmail`, this event can be useful for monitoring but can be skipped entirely. The reason for failure can be sent whenever this event is triggerred

**Comment by rishabhpoddar** [comment]
# Feedbacks
- [ ] Output of these functions can be custom since the user can customize the API in the backend to return whatever they like
    -  `{ status: "EMAIL_ALREADY_VERIFIED_ERROR" | "OK" | "CUSTOM_RESPONSE", fetchResponse: ... }`
    - We always want to check the status of the API response and if the status is missing, or one that we don't recognise, then we return `{status: "CUSTOM_RESPONSE", fetchResponse: ...}`
- [ ] Add preAPIHook to all these functions
- [ ] Add recipe interface + user exposed functions
- [ ] Edit the contributing guide to have these principles for custom input / output.
- [ ] Add the init function signature as well.
- [ ] You don't need Hooks / events
- [ ] If a status of `GENERAL_ERROR` is returned from the API call, it is thrown as a JS error with that custom message from the function.

**Comment by nkshah2** [comment]
```ts
// Recipe init types

type PreAPIHookContext = {
    action: "VERIFY_EMAIL" | "SEND_VERIFY_EMAIL" | "IS_EMAIL_VERIFIED";
    requestInit: RequestInit;
    url: string;
};

type RecipeConfig = {
    recipeId: string;
    appInfo: NormalisedAppInfo;
};

type NormalisedRecipeConfig = {
    recipeId: string;
    appInfo: NormalisedAppInfo;
}

type InputType = RecipeConfig & {
    mode?: "OFF" | "REQUIRED";
    disableDefaultImplementation?: boolean;
    preAPIHook?: (context: PreAPIHookContext) => Promise<{ url: string; requestInit: RequestInit }>;
    signOut(): Promise<void>;
    override?: {
        functions?: (
            originalImplementation: RecipeInterface,
            builder?: OverrideableBuilder<RecipeInterface>
        ) => RecipeInterface;
    };
}

export type NormalisedConfig = NormalisedRecipeConfig & {
    mode: "OFF" | "REQUIRED";
    disableDefaultImplementation: boolean;
    preAPIHook: (url: string; requestInit: RequestInit) => Promise<{ url: string; requestInit: RequestInit }>;
    signOut(): Promise<void>;
    override: {
        functions: (
            originalImplementation: RecipeInterface,
            builder?: OverrideableBuilder<RecipeInterface>
        ) => RecipeInterface;
    };
};

function init(config?: InputType)

// Recipe interface function types

type RecipeFunctionOptions = {
    preApiHook: (context: PreAPIHookContext) => { url: string; requestInit: RequestInit },
};

// Each function will check if the status in the API response matches an expected value 
// and return "CUSTOM_RESPONSE" if it does not

// Each function will return a status in the response to keep typing consistent, 
// for example isEmailVerified no longer returns just a boolean value

// Each function must support {status: "OK" | "CUSTOM_RESPONSE", fetchResponse: Response} as a bare minimum. 
// Functions that dont rely on API calls can skip {status: "CUSTOM_VALUE"} and fetchResponse

// Functions will specifically throw errors if the API responds with "GENERAL_ERROR" using 
// the message from the API as the error message

export type RecipeInterface = {
    verifyEmail: (input: {
        token?: string;
        config: NormalisedConfig;
        options?: RecipeFunctionOptions;
    }) => Promise<{
        status: "EMAIL_VERIFICATION_INVALID_TOKEN_ERROR" | "OK" | "CUSTOM_RESPONSE",
        fetchResponse: Response,
    }>;

    sendVerificationEmail: (input: {
        config: NormalisedConfig;
        options?: RecipeFunctionOptions;
    }) => Promise<{
        status: "EMAIL_ALREADY_VERIFIED_ERROR" | "OK" | "CUSTOM_RESPONSE",
        fetchResponse: Response,
    }>;

    isEmailVerified: (input: {
        config: NormalisedConfig;
        options?: RecipeFunctionOptions;
    }) => Promise<{
        status: "OK" | "CUSTOM_RESPONSE",
        isVerified: boolean,
        fetchResponse: Response,
    }>;
};
```

**Comment by nkshah2** [comment]
Effects in auth-react SDK

> pre API hook in auth react (the API for that should not change)

The web-js SDK uses the same signature for recipe level preAPIHooks so this should remain unchanged. The auth-react SDK can pass the preAPIHook as is when initialising the web-js recipe

> Removing of recipe interface and recipeImplementation files.

These files will not need to be removed. Since web-js wont require onHandleEvent the auth-react SDK would fire these events when calling web-js methods. The only change will be in function implementations that will change from 

```ts
function recipeFunction() {
    executeSomeLogic()
    callEventHandler()
}
```

to

```ts
function recipeFunction() {
    webJs.recipeFunction()
    callEventHandler()
}
```

> Sending event hooks - how would that happen.

Same as above

> Handling general errors or custom responses?

General errors will be thrown as javascript `Error`s, so no special handling for this will be needed. For custom responses the auth-react SDK will require changes (method return types will need to change, method logic for checking `status` will need to change etc)
