### ISSUE TITLE
Please Add some working docs to make it easy for folks get started.

### ISSUE THREAD

**Issue by arbhassan** [supertokens/supertokens-web-js#51]
The current docs for Plain JavaScript are very vague and don't provide a clear path like the docs for React. 

I couldn't even setup a basic working example with it. No idea of which functions to use etc.

**Comment by rishabhpoddar** [comment]
This is in progress. We should have docs for this soon. Until then, you can refer to an example app: https://github.com/supertokens/supertokens-web-js/tree/example-vue-tpep/examples/vuejs/with-thirdpartyemailpassword

**Comment by rishabhpoddar** [comment]
Docs for building with custom UI has been added now.
