### ISSUE TITLE
TypeError in Passwordless.init

### ISSUE THREAD

**Issue by makeitcount** [supertokens/supertokens-web-js#59]
Getting error in init function when using `contactMethod` option

Error
> Argument of type '{ contactMethod: string; }' is not assignable to parameter of type 'UserInput'.Object literal may only specify known properties, and 'contactMethod' does not exist in type 'UserInput'.This is how my init fn looks like

```
SuperTokens.init({
      appInfo: {
          apiDomain: "http://localhost:3000",
          apiBasePath: "/api",
          appName: "SuperTokens-Passwordless-Demo",
      },
      recipeList: [
          Session.init(),
          Passwordless.init({
            contactMethod: "EMAIL_OR_PHONE" //ERROR here
          }),
      ],
    });
```

**Comment by nkshah2** [comment]
Hey @makeitcount , thanks for reporting the issue.

`supertokens-web-js` does not accept any property `contactMethod` when initialising the Passwordless recipe. Im closing this issue since there is no real fix here, if you feel like this warrants additional attention feel free to reopen it
