### ISSUE TITLE
Support Web Extension MV3 service worker as context

### ISSUE THREAD

**Issue by sublimator** [supertokens/supertokens-web-js#62]
Google are aggressively moving everyone to Manifest Version 3 for Web Extensions.
This change moves the background page to an ephemeral Service Worker. 
localStorage and other window objects are no longer available 
This library sadly won't work

**Comment by rishabhpoddar** [comment]
How would you go about persisting data in that case?

We also allow you to override the window functions used by the lib (see https://github.com/supertokens/supertokens-web-js/blob/master/lib/ts/types.ts#L60 and https://github.com/supertokens/supertokens-web-js/blob/master/lib/ts/types.ts#L48) - would this help?

**Comment by sublimator** [comment]
Thanks for the links! 
Yes, maybe that's enough :)

> How would you go about persisting data in that case?
There are various options: IndexedDB, Web Extension storage apis etc

**Comment by sublimator** [comment]
From our extensions background page we are able to make authenticated requests to our website, using cookies that are set by the website. However, it's not uncommon for users to not visit the website for long periods, while using the extension daily. This means that we must refresh tokens from in the extension. 

Am I right that these are SuperTokens cookies? 
```
sIRTFrontend=b86ee1ce-41a9-4e05-a1dc-5543ee7d8dca; 
sFrontToken=eyJ1aWQiOiI....TQwZDQtYTQxNS 
```
What do these do? 
We would need to set these cookies somehow on the website domain?

**Comment by sublimator** [comment]
Thanks!

**Comment by sublimator** [comment]
It seems `window` must be defined to get `fetch` 
https://github.com/supertokens/supertokens-website/blob/master/lib/ts/fetch.ts#L166

**Comment by rishabhpoddar** [comment]
Hmmm. You could set `global.window = {fetch: ..., ...}` perhaps before calling supertokens.init. Will that not work?

**Comment by sublimator** [comment]
Yeah, I did do that and it got past the error, but I would prefer not to

**Comment by rishabhpoddar** [comment]
Fair enough. We will figure something for that

**Comment by sublimator** [comment]
Thanks! I will let you know if I come across anything else

**Comment by sublimator** [comment]
@rishabhpoddar 

So I cloned the `supertokens-website` repo ( sorry, I opened this issue in the wrong repository ) and did some find usages and the only internal usages I found for the window handler seemed to be location.getHostName() and location.getOrigin(). 
There seemed to be none for the cookie handler. 

Does this repo (`supertokens-web-js`) make more use of the interfaces ?

**Comment by rishabhpoddar** [comment]
Cookie handler is being used in supertokens-website as well. See this as an example: https://github.com/supertokens/supertokens-website/blob/master/lib/ts/fetch.ts#L555

**Comment by sublimator** [comment]
So, my IDE must have got confused as well :) 
It wasn't showing that usage
I'll take a further look

**Comment by sublimator** [comment]
@rishabhpoddar 

Hi, so it seems the browser-tabs-lock module also assumes a window environment with localStorage:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/525211/189315840-30bb5433-ffb2-43d5-ba9c-8db2a2c3f065.png">

**Comment by rishabhpoddar** [comment]
Ah right!! Thanks. Will modify this as well.

**Comment by sublimator** [comment]
Thanks!

**Comment by sublimator** [comment]
Any update here @rishabhpoddar  ?

**Comment by rishabhpoddar** [comment]
hey @sublimator none yet - sorry. Didn't get bandwidth to do this and probably won't be done anytime soon. 

You may want to fork browser tabs lock and change that part of the code and use your forked version instead of what we use.

**Comment by sublimator** [comment]
@rishabhpoddar 

Could you take a quick look at this please and see if it will fly ?

https://github.com/supertokens/supertokens-website/pull/186

**Comment by rishabhpoddar** [comment]
@sublimator i have merged the PR and added it to our test pipeline. Once that's tested, i'll release the SDK and close this issue.

**Comment by sublimator** [comment]
Maybe I should make a PR to fix "window must be defined to get fetch" ?

**Comment by sublimator** [comment]
```
AuthHttpRequest.env = getWindowOrThrow().fetch === undefined ? global : getWindowOrThrow();
```

I believe you could just set that to `self` and it would work. 
Do you need to support relic browsers ? 

Actually, I don't quite understand that `global` reference. 
What is that there to support?  Given it will throw if it can't find window?

**Comment by porcellus** [comment]
We are adding a new getWindowUnsafe method to window handler reference in the next release of the website SDK. I think providing that override, and returning `self` would solve the "window must be defined to get fetch" issue.
Could you try using this https://github.com/supertokens/supertokens-website/tree/15.0 branch to see if it resolves your issue?

**Comment by sublimator** [comment]
That /seems/ to work, but it's the end of the day and I haven't tested thoroughly 
Can get you more info tomorrow, otherwise 15.0 looks pretty good

**Comment by rishabhpoddar** [comment]
@sublimator we have released the new version of the SDK on npm (v15.0.0).

**Comment by rishabhpoddar** [comment]
@sublimator i have also added you to the readme on the supertokens-core repo :) Thanks

**Comment by sublimator** [comment]
@rishabhpoddar 

Hey, sorry, I missed the notification, 

A very late "thank you!!"  :)
