### ISSUE TITLE
Is Supertokens-web-js really open source?

### ISSUE THREAD

**Issue by marchalb** [supertokens/supertokens-web-js#63]
Many sections of the library (like all the files in the bundle directory ) are completely unreadable .. one can't analyse the code for debugging purpose.  How to get a readable version of Supertokens-web-js?

**Comment by rishabhpoddar** [comment]
See this here: https://github.com/supertokens/supertokens-web-js/tree/master/lib/ts

**Comment by marchalb** [comment]
thanks .. actually I finally got it .. a good part of the 'clean code' is in the 
supertokens-website. repository .  The bundle mix the two ..
One has to look at both repository to try to understand what a problem is .

**Comment by rishabhpoddar** [comment]
Yea.. the supertokens-web-js depends on supertokens-website for the session recipe part.
