### ISSUE TITLE
Fix typos on the route /sessionInfo

### ISSUE THREAD

**Issue by Zaker237** [supertokens/supertokens-web-js#69]
Hi every one i will start by giving you all guys a big thank you for the amazing project and for this example that really help me.

Going through this example a figure out that there is a type on the `/sessioninfo` route. In the [HomeView](https://github.com/supertokens/supertokens-web-js/blob/master/examples/vuejs/with-thirdpartyemailpassword/src/views/HomeView.vue#36) on the Frontend, the name is `sessionInfo` written with a capital `I` but on the [backend side](https://github.com/supertokens/supertokens-web-js/blob/master/examples/vuejs/with-thirdpartyemailpassword/api-server/index.ts) the route has `sessioninfo` but without capital `I`. It takes me a fews hours to get that and i think that should be fixed to help others people that try this project.

**Comment by rishabhpoddar** [comment]
hey @Zaker237 thanks! We have fixed this.
