### ISSUE TITLE
URL path normaliser shouldn't drop query params

### ISSUE THREAD

**Issue by davidknezic** [supertokens/supertokens-web-js#82]
I'm running into an issue while trying to get [supertokens/supertokens-auth-react](https://github.com/supertokens/supertokens-auth-react) to redirect the client after login.

When the client visits `/protected?foo=bar` while unauthorized, I redirect them to `/auth?redirectToPath=${encodeURIComponent('/protected?foo=bar')}`.

However, after successful login, the client only gets recirected to `/protected`, losing any original query params. I could pinpoint the issue to [/lib/ts/normalisedURLPath.ts](/lib/ts/normalisedURLPath.ts), which only respects the `pathname`, but ignores the properties `URL.search` and `URL.hash` (only relevant on client-side).

https://github.com/supertokens/supertokens-web-js/blob/09b6c85685cfb668ee244380996e230b333fbd1f/lib/ts/normalisedURLPath.ts#L37-L77

**Comment by rishabhpoddar** [comment]
This has been fixed in supertokens-auth-react version >= 0.31.2
