### ISSUE TITLE
Cookie not included in requests to server, 401 response

### ISSUE THREAD

**Issue by notflip** [supertokens/supertokens-web-js#87]
I've set up an example following the documentation, however when I try to hit a protected route I get a 401 error.
**I've tried both axios and the native fetch in VueJS.**

_Protected Route in NodeJS_
```
app.get("/check", verifySession(), (req: SessionRequest, res: Response) => {
    if (req.session) {
        res.end('Authorized!');
    }
    else {
        res.end('Is not Authorized');
    }
});
```

_Session is active in my frontend (vue)_
```
SuperTokens.init({
  appInfo: {
    appName: "SuperTokens Vue ThirdPartyEmailPassword Example",
    apiDomain: "http://127.0.0.1:3001",
  },
  recipeList: [
    // EmailVerification.init(),
    EmailPassword.init(),
    Session.init()
  ],
});
```

_These are the sent request headers (seen in Chrome inspector)_
```
GET /check HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Connection: keep-alive
Host: localhost:3001
Origin: http://127.0.0.1:5173
Referer: http://127.0.0.1:5173/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="112", "Brave";v="112", "Not:A-Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

## Edit, if I log a message in the Session recipe init, I get the following message
`====== Session does not exist. Are you sending the session tokens in the request with the appropriate token transfer method?`

Using
```
Session.init({
    errorHandlers: {
        onUnauthorised: async (message, request, response) => {
            console.log('======', message)
        }
    },
}),
```

**Comment by rishabhpoddar** [comment]
When you query the API, what domain are you using? Are you using http://127.0.0.1:3001?

When you sign in, the set-cookie headers are sent in the response, do you see an orange triangle at the end of the set-cookie header value? If yes, what message is shown when you hover on it?

**Comment by notflip** [comment]
@rishabhpoddar Thanks for getting back, I don't see a triangle with information in the inspector. 

![Screenshot 2023-04-17 at 07 45 34](https://user-images.githubusercontent.com/4146384/232393519-522b346a-511d-47de-aa66-9e76065c1c32.png)

**Comment by notflip** [comment]
@rishabhpoddar My bad, I had localhost mixed up in my axios request, Closing this.
