### ISSUE TITLE
 Error: SuperTokensWindowHandler must be initialized before calling this method.

### ISSUE THREAD

**Issue by sachinshilwal** [supertokens/supertokens-web-js#88]
I have an app in Vue3 (using pnpm).
I am using `ThirdPartyEmailPassword` recipe, which is working fine. But when I try to integrated google sign in with it, it is giving error. 
My code for google signin looks like this:
```
import { getAuthorisationURLWithQueryParamsAndSetState } from "supertokens-web-js/recipe/thirdpartyemailpassword";

async function googleSignIn(redirectURL: string) {
  try {
    const authUrl = await getAuthorisationURLWithQueryParamsAndSetState({
      authorisationURL: `${redirectURL}/auth/callback/google`,
      providerId: "google",
    });

    window.location.assign(authUrl);
  } catch (err: any) {
    if (err.isSuperTokensGeneralError === true) {
      window.alert(err.message);
    } else {
      window.alert(`Oops! Something went wrong.${err.message}`);
    }
  }
}

export default googleSignIn;
```
And Error is:
` Error: SuperTokensWindowHandler must be initialized before calling this method.`

BTW my initialization looks something like this:
```
 SuperTokens.init({
    appInfo: {
      apiDomain: baseURL,
      appName: appTitle,
      apiBasePath: "/auth",
    },
    recipeList: [Session.init(), ThirdPartyEmailPassword.init()],
  });
```

**Comment by sachinshilwal** [comment]
@nkshah2 yes. I just checked it in my `node_modules` and `supertokens-website` is also there.

**Comment by nkshah2** [comment]
Hi @sachinshilwal,

I tested with both npm and pnpm and it works fine for me. Can you provide a small sample repo where you can re-create the issue and also include the full error stacktrace? I've included a zip of a fresh Vue project generated with pnpm that uses supertokens-web-js in a similar way where the code works fine. (Note that supertokens-web-js is used in the `components/TheWelcome.vue` file)

[vue-project.zip](https://github.com/supertokens/supertokens-web-js/files/11247093/vue-project.zip)

**Comment by rishabhpoddar** [comment]
@sachinshilwal were you able to fix the issue? What was the problem?

**Comment by sachinshilwal** [comment]
@rishabhpoddar no actually.
But I think there is something wrong with my setup.

**Comment by rishabhpoddar** [comment]
I see. Please let us know what the issue was @sachinshilwal . Thanks
